version: '3'
services:

    dynamodb-local:
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
      image: "amazon/dynamodb-local:latest"
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      volumes:
        - "./database/dynamodb:/home/dynamodblocal/data"
      working_dir: /home/dynamodblocal

    fastapi-app:
      build: .
      container_name: app-node
      # command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
      volumes:
          - .:/code
      ports:
        - "80:80"
      depends_on:
        - "dynamodb-local"
      links:
        - "dynamodb-local"
      environment:
        AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
        AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
        REGION: 'ap-southeast-1'